### ISSUE TITLE
ImageLibrary to support Laravel Storage disks

### ISSUE THREAD

**Issue by markszymik** [robsontenorio/mary#259]
Could we possibly include support for Laravel Storage disks in ImageLibrary component?
 
Currently, this component supports multiple files exclusively with the local filesystem.

It would be an additional parameter in syncMedia method:    
        
```php
$this->syncMedia(
    model: $this->user,         // A model that has an image library
    files: $this->files,        // Temporary files to sync
    library: $this->library,    // The library metadata
    storage_subpath: '',        // Sub path on storage. Ex: '/users'
    model_field: 'library',     // The model field that represents the library metadata
    visibility: 'public'        // Visibility on storage
    disk: 's3'                    // Specify traget disk
);
```

**Comment by robsontenorio** [comment]
@markszymik  

Here is WIP version. Can you check?


```sh
composer require robsontenorio/mary:dev-imagelibrary-storages
php artisan view:clear
```

**When released I will add this note on docs:**

Make sure to proper configure CORS CDN on your S3 provider for your local and production environment. Otherwise cropper won't work.


**TODO:**
- [ ] Remove old files from storage when there is some change
