### ISSUE TITLE
Leaflet Map

### ISSUE THREAD

**Issue by IamSAB** [robsontenorio/mary#304]
[Leaflet](https://leafletjs.com/) is JavaScript library for mobile-friendly interactive maps.

In my opinion it is the easiest option to add map without clutter and it has a lot of plugins. Would be nice to have it included similar to the chart component, where you could add markers and layers from php code.

**Comment by robsontenorio** [comment]
That library heavily relies on JS methods to be able to work (add layers, markers, popup …).

And because that we are not able to set it up with PHP as easy as other third party library from maryUI. 

 ChartJS has a different approach: we can make it work only with properties. 
 
Thanks for your suggestion!
