### ISSUE TITLE
Use of dymanic properties is not allowed

### ISSUE THREAD

**Issue by rabol** [robsontenorio/mary#466]
### maryUI version

1.32

### daisyUI version

4.11.1

### Livewire version

3.5.0

### What browsers are affected?

Chrome

### What happened?

When using a Table component, the internal code have this:

```
 @php 
    # helper variable to provide the loop context
    $this->loop = $loop;
@endphp
```

That will cause a warning in php

[12:02:12] LOG.warning: Creation of dynamic property App\Livewire\CustomerGroups\Index::$loop is deprecated in /xxxx/xx/xx/xx/xx/storage/framework/views/91e4542c249e53580c8017a23412b26f.php on line 134

This occurs if you use the  Table component in a normal Livewire component - the warning does not seems to appear in a Volt component

**Comment by robsontenorio** [comment]
I have created a Livewire component with this code and can't reproduce it. What settings do you have to enable these warnings?

```blade
<div>
    @php
        $users = App\Models\User::take(5)->get();

        $headers = [
            ['key' => 'id', 'label' => '#'],
            ['key' => 'name', 'label' => 'Nice Name'],
        ];
    @endphp

    <x-table :headers="$headers" :rows="$users" striped @row-click="alert($event.detail.name)" />
</div>

```

**Comment by rabol** [comment]
```
<x-card>
    <x-table :headers="$headers" :rows="$customerGroups" @row-click="$wire.showEdit($event.detail)" :sort-by="$sortBy" with-pagination>
        @scope('actions', $customerGroup)
            <x-button wire:click="delete('{{ $customerGroup->id }}')" icon="o-trash" class="btn-sm btn-ghost text-error" wire:confirm="Are you sure?" spinner />
        @endscope
    </x-table>
</x-card>
```

**Comment by robsontenorio** [comment]
The reason is because we are exposing this variable to make access to `$loop` on outside context work.
https://mary-ui.com/docs/components/table#loop-context

![image](https://github.com/robsontenorio/mary/assets/118955/8ef18560-a2cf-4331-8ed0-8b2a2468c53d)

![image](https://github.com/robsontenorio/mary/assets/118955/b894782d-1a88-4a45-bc8f-c581f8a8e1a1)


I will hold for now, because I don't have a better solution. If someone could handle this I appreciate.
